[book]
authors = ["Near Inc <hello@nearprotocol.com>"]
multilingual = false
src = "src"
title = "The Nearnomicon"
description = "Implementation details of the NearProtocol client"

[build]
build-dir = "docs"

[output.html]
mathjax-support = true
